### ISSUE TITLE
dhcp proxy not responding to pxe once machine is in list

### ISSUE THREAD

**Issue by brunnels** [digitalrebar/provision#1037]
While dhcp is in proxy mode it will serve pxe if the machine is not listed in the machines list and there is not a reservation for the machine mac address.

It looks like what is happening is:
- machine boots up and is not in the machine list offerNetBoot get set to true on line 232 of dhcp.go
- the machine boots and gets added to the machine list
- then reboot the machine and it tries pxe again
- this time it doesn't match line 223 because the machine is in the list
- there is no address because it's a fake lease so it matches line 254 and offerNetBoot gets set to false
- then when it gets to line 670 it returns NoPXE because offerNetBoot is false

**Comment by svallebro** [comment]
Nice issue description, this happens for me too.

It has work in some previous release, I'm sorry that I can not recall what upgrade made it fail for me.
