### ISSUE TITLE
DHCP option 43 never renders into offer packet

### ISSUE THREAD

**Issue by KernelTom1** [digitalrebar/provision#1088]
Trying to define iDRAC specific options as outlined in https://www.dell.com/support/manuals/us/en/19/poweredge-c6400/idrac_3.15.15.15_ug/dhcp-options?guid=guid-a15098af-6b6c-4417-afd6-1b4c0467973a&lang=en-us
After speaking with vlowther, determined we should use format in subnet definition as follows:
{
      "Code": 43,
      "Value": "string:{{ if (eq (index . 60) \"iDRAC\") }} -f R640-config.json -i 10.101.197.34 -s http -po 8091 {{end}}"
    }
Doing so never shows option 43 going into the offer packet

**Comment by VictorLowther** [comment]
Should be fixed by https://github.com/digitalrebar/provision/pull/1095
