### ISSUE TITLE
add remote HTTP/S support for "isos upload"

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#1090]
Currently (v3.12.0-tip-139) we do not support:

`drpcli isos upload http://get.rebar.digital/images/VMware-VMvisor-Installer-6.7.0.update01-10302608.x86_64.iso as VMware-VMvisor-Installer-6.7.0.update01-10302608.x86_64.iso`

Would be a nice addition to be able to get a remote HTTP resource and upload it as an ISO

**Comment by galthaus** [comment]
Done! #1091
