### ISSUE TITLE
drpcli contents convert does NOT handle secure parameters in the content package.

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/provision#1093]
The drpcli contents convert command takes a content package and converts it into read/write objects by creating them one at a time.  Currently, objects can not be created with secure parameters.  So, either create needs to auto-secure parameters that are secure parameters on create or convert needs to create objects without parameters and then set the parameters in a second action.

Not sure which why if either we should go right now.  Leaving for later thought and execution.

**Comment by VictorLowther** [comment]
Fixed in https://github.com/digitalrebar/provision/pull/1085
