### ISSUE TITLE
update from ubuntu-18.04.1-server-amd64.iso to ubuntu-18.04.2-server-amd64.iso

### ISSUE THREAD

**Issue by isnuryusuf** [digitalrebar/provision#1122]
on drp-data/saas-content/default.yaml ubuntu-18.04.1-server-amd64.iso is not avaiable anymore, change to ubuntu-18.04.2-server-amd64.iso

 IsoFile: ubuntu-18.04.2-server-amd64.iso
        IsoSha256: a2cb36dc010d98ad9253ea5ad5a07fd6b409e3412c48f1860536970b073c98f5
        IsoUrl: http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.2-server-amd64.iso

**Comment by sygibson** [comment]
@isnuryusuf - thank you for providing the appropriate links - we have already updated the Ubuntu Bionic bootenv - you can find it in `tip` version of the `drp-community-content` - we should be updating `stable` version soon with the new bootenv version.
