### ISSUE TITLE
DHCP Proxy mode only works for unknown machines

### ISSUE THREAD

**Issue by hberntsen** [digitalrebar/provision#1158]
Discussed in #community on slack: https://rackn.slack.com/archives/C02L9P26Q/p1554897231342900

We use drp v3.12 with an OpenWRT dnsmasq server. The dnsmasq server is responsoble for DHCP, drp is running in proxy mode.

The first time a host boots, it will boot sledgehammer. When we reboot that machine it fails to boot. Wireshark shows that the second time drp does not answer the `DHCP Discover`. The host has a static ip. Removing the host from the machines tab will let it boot again.

Used hardware:
- Raspberry Pi 1 with OpenWRT
- Nexcom NDiS 126 as drp server
- Intel NUC7i3BNH as PXE client (same behaviour in UEFI boot  in legacy PXE)
- Nexcom NDiS 126 as PXE client
- HPE OfficeConnect 1920 switch

Both PXE clients show the same behavior.

We have a wireshark trace: https://rackn.slack.com/archives/C02L9P26Q/p1554897314343400

Update:
With proxy mode disabled sledgehammer continues to boot successfully after a reboot.

Update:
Here is the drb dhcp debug log with associated pcap file: https://rackn.slack.com/archives/C02L9P26Q/p1554902063359800?thread_ts=1554897136.340700&cid=C02L9P26Q

Update:
The behavior is the same without the checkpoint DHCP in the network.

**Comment by bjwschaap** [comment]
@galthaus did you have any chance yet to take a look at this issue?

**Comment by hberntsen** [comment]
Looks like the new digital-rebar version fixed this problem
