### ISSUE TITLE
ESXi install on HPE Moonshot cartridges fails

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#1193]
Currently, the ESXi moonshot cartridges ESXi install process has an issue with the python callback to DRP to mark the install successful.  This appears to be a timing issue during the install in the `%post` section.  

Additional investigations are required to determine what is causing the problem.

The same python code is rendered by Weasel to `/tmp/ks-script`, and when it is run manually at the ESXi DCUI shell, it runs successfully.

**Comment by sygibson** [comment]
Current `vmware` plugin includes a `sleep` timer after making the firewall change to let the firewall services "settle" prior to making the `urllib` python call.  This has not been tested yet, waiting for access to the moonshot hardware.

**Comment by galthaus** [comment]
This has been validated to resolve the issue.
