### ISSUE TITLE
UX: on Machines detail, clicking `boolean` type hides the value

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#1217]
for large customer

When displaying Machines Detail panel, you can click on the icon for the Object Type (eg double quote for string).  Clicking on this toggles the displayed view. 

When clicking on Boolean types the "slider" icon disappears and leaves the display column blank - it does not output `true` or `false` in text as expected.

This has led some operators to think the value (boolean `true`) was removed from the machine, when in fact, it has not been.

**Comment by Meshiest** [comment]
Resolved
