### ISSUE TITLE
UX: Machines Detail panel has greyed out "save" and "cancel" - causes confusion

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#1218]
for a very large customer

The Machines Detail page has a `save` and `cancel` button on the bottom of the pop-out panel, even though the machine is not in `edit` mode.  This has caused some operators confusion about editing the machine object details.

Suggest removing the `save/cancel` buttons in favor of an (additional) `Edit` button at the bottom that will reinforce that this is a read-only panel - and an operator must explicitly click `Edit` to enter editing mode.   This is in addition to the `edit` button in upper right.

Possibly add a highlighted note in the read-only view of the Machines Detail page as follows:

![Screen Shot 2019-05-21 at 13 08 14](https://user-images.githubusercontent.com/5308433/58127403-2d972080-7bca-11e9-8af3-b7a71e980407.png)

**Comment by zehicle** [comment]
This makes sense to me and should be an easy change

**Comment by zehicle** [comment]
fix in queue
