### ISSUE TITLE
UX can't add/edit inline task templates due to incorrect PATCH

### ISSUE THREAD

**Issue by mclamb** [digitalrebar/provision#140]
It is very difficult to edit content in inline task templates in the UX. It's hard to say the exact process that determines whether or not inline task templates can be edited, but I find that generally trying to edit or add content does not work. I must first add a number of dummy inline template tasks with edit, then conduct some deletions before the primary.

This seems to be an error with the PATCH command that is submitted. When I edit content the PATCH operation is usually a remove when it should probably be a POST for brand new content.

**Comment by Meshiest** [comment]
this should be fixed
