### ISSUE TITLE
UX bug: Content packs have a blank entry in the Bundle column

### ISSUE THREAD

**Issue by mclamb** [digitalrebar/provision#163]
In the default UX view items underneath PROVISION and CONTROL, the Bundle column is blank for content packs. It shows the Bundle if the item in question comes from a Plugin but not regular Content Packs. This seems to be the case for stages, tasks, templates, params, profiles, and bootenvs.

**Comment by Meshiest** [comment]
I don't think this is a UX bug

**Comment by galthaus** [comment]
It is mostly fixed in v4.3.0. It appears that content packs may still have the issue.  @VictorLowther

**Comment by galthaus** [comment]
@VictorLowther - I'm looking at it real quick.  It is a server side bug fixed in v4.3.0.
