### ISSUE TITLE
Update sledgehammer choose a machine specific file first

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/provision#164]
Currently, the discovery and sledgehammer bootenvs share the start-up.sh script.  This means that the file is never rendered with a machine.  This makes the generateToken function currently has to make the unknown token have a "get" claim on machines to handle the fact that the start-up script when driven by the sledgehammer bootenv needs to read the machine.  This can be fixed by making sledgehammer get the machine specific start-up.sh script (by UUID in kernel proc line) or current behavior if UUID is not present.

**Comment by galthaus** [comment]
The only remaining part of this is that the non-create path uses a get to check for a HOSTNAME.  This could be removed by changing the DHCP server to check for a machine that has the requested IP and populate the Hostname Option based upon it.  This would only apply to DRP served DHCP replies.  Hmm.    Maybe we shouldn't fix this.

**Comment by sygibson** [comment]
believe fixed - @galthaus to validate
