### ISSUE TITLE
UX bug: Navigating file store does not URL encode special characters

### ISSUE THREAD

**Issue by mclamb** [digitalrebar/provision#166]
When navigating the file store in the UX in stable or tip special characters are not properly URL encoded making it impossible to go further if the item is a directory without manually changing the contents in the URL bar.

For example:

Click on the drpcli tip folder that contains a "+" in it and it will try to go to:

{{ ProvisionerUrl }}/files/rebar-catalog/drpcli/v4.3.0-beta1.5+g3557f4782d5ab750e2a43c2243ba114b418fe90a/

It should encode it thus:

{{ ProvisionerUrl }}/files/rebar-catalog/drpcli/v4.3.0-beta1.5%2Bg3557f4782d5ab750e2a43c2243ba114b418fe90a/

**Comment by Meshiest** [comment]
fixed
