### ISSUE TITLE
UI should have refresh buttons instead of having to refresh screen

### ISSUE THREAD

**Issue by zehicle** [digitalrebar/provision#217]
even better if they were on a background timer

**Comment by wdennis** [comment]
Maybe both a "refresh" button and a auto-refresh setting allowing auto-refresh every 'n' sec's (some of us don't like the auto-refresh ;)

Even better yet, use AJAX to update sections based on events ;)

**Comment by zehicle** [comment]
resolved.  recent change creates live updates for lists
