### ISSUE TITLE
Ubuntu 16.04 install: DRP U1604 ISO repo overwrites std Ubuntu repos in /etc/apt/sources.list

### ISSUE THREAD

**Issue by wdennis** [digitalrebar/provision#234]
After installing Ubuntu 16.04 via DRP, I went to install some software I normally install right after a new install completes (some examples are 'ethtool' and 'tree' packages.) Upon apt informing me it couldn't find them, I investigated the sources available in /etc/apt, and found that the only source there was the DRP Ubuntu ISO one (http://{DRP-IP}:8091/ubuntu-16.04/install stable restricted)

I feel this change would be unsuspected by a regular user. I would suggest either:
1) Do not overwrite the standard Ubuntu-provided sources.list file, or
2) Provide a setting (property?) to allow the user doing the install to select either keeping the std Ubuntu repo sources (default), or restricting the sources to only the DRP server's ISO one (perhaps useful in the case of a non-Internet connected node.)

**Comment by galthaus** [comment]
This is now a sub template and can controlled by parameters.  See the docs architecture/data/templates.
