### ISSUE TITLE
Invalid github link in /doc/api  

### ISSUE THREAD

**Issue by StephenTames** [digitalrebar/provision#380]
The address cannot be processed
Input:
.. swaggerv2doc:: https://github.com/digitalrebar/provision/releases/download/tip/swagger.json

Output:
Unable to process URL: https://github.com/digitalrebar/provision/releases/download/tip/swagger.json. Please check that the URL is a valid Swagger api-docs URL and it is accesible

**Comment by sygibson** [comment]
resolved - transient error - corrected
