### ISSUE TITLE
Reservations should not always use two hours for lease

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/provision#414]
if reservation value is non-zero, then use it.
If subnet exists, then use the reserve time.
If !subnet exists, then use a preference.
If nothing exists, use 2 hours.

**Comment by galthaus** [comment]
This still needs to be fixed at line 61 of midlayer/dhcp.go

**Comment by sygibson** [comment]
not fixed

**Comment by sygibson** [comment]
not done - needs fixed ....

**Comment by galthaus** [comment]
This is now fixed by some of the Apple support work.

**Comment by galthaus** [comment]
Okay so -  this is fixed.  There isn't a pref.  Everything comes from the subnet.  The part that is now missing is that the Reservation has an integer field Duration that defines lease time.

**Comment by galthaus** [comment]
Okay - now this is fixed.  The UI has a way to set the duration.  If nothing is set, the default is 7200 seconds.  The rest is now drivable from lots of ways including direct configuration.
