### ISSUE TITLE
Enable local FS, HTTP/S endpoint for passing JSON blob 

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#447]
currently several "create" command constructs can take in YAML or JSON blobs ... I assumed one could pass a JSON/YAML file in directly.  However, this is not the case ... the correct construct is:

  drpcli contents create - < foo.json 

Clearly this constructs works - but it would be a nice "fit-n-finish" enhancement to be able to do something along the following:

   drpcli contents create directory/file.json
or
   drpcli contents create https://example.com/directory/file.yaml

I believe there is a standard Go library that enables this flexible input format.

**Comment by galthaus** [comment]
Addressed by #583

**Comment by sygibson** [comment]
completed in 3.4.0
