### ISSUE TITLE
right side pop-out panels can't be dismissed

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#465]
Sometimes on Edit of a right pop-out panel, after clicking "add" or "save", the UI basically "freezes" - I can't dismiss the pop-out panel - I have to reload the page ... or click on a menu entry in the left menu panel. 

An example:

  Profiles --> Clone Profile (k8s-deploy) --> make changes --> Click "Add"

**Comment by zehicle** [comment]
duplicate of #504
