### ISSUE TITLE
Add "embedded_assets" override to dr-provision

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#469]
Currently - the embedded/assets/ content overwrites content on disk.  If a bug is observed in the field, it's tough to replace this content to debug/enhance/fix any potential issues, forcing an operator to have to do a full upgrade (or binary replacement) of the dr-provision service. 

This enhancement requests the addition of a new flag to the dr-provision service that allows for an "embedded assets" override location to be provided.  If a piece of content exists there (for example "explode_iso.sh" - then use that asset as the reference material, and skip extracting the actual embedded asset in the binary.

**Comment by galthaus** [comment]
Addressed by #583

**Comment by sygibson** [comment]
startup flag added to override the embedded assets content location
