### ISSUE TITLE
Sledgehammer doc out-of-date

### ISSUE THREAD

**Issue by CoRfr** [digitalrebar/provision#47]
I was looking at the https://github.com/digitalrebar/provision/blob/v4/doc/arch/sledgehammer.rst / https://provision.readthedocs.io/en/latest/doc/arch/sledgehammer.html doc and it seems like the repository referenced, https://github.com/digitalrebar/sledgehammer , doesn't exist anymore.

Is there any chance someone could update the doc to reflect the new state of things?

**Comment by kapsh** [comment]
Looks like it leaves in https://github.com/digitalrebar/provision-content/tree/v4/sledgehammer-builder now.

**Comment by galthaus** [comment]
@kapsh - for the win.
