### ISSUE TITLE
Documentation link on rebar.digital is broken

### ISSUE THREAD

**Issue by rothgar** [digitalrebar/provision#470]
Link on http://rebar.digital/#install leads to http://provision.readthedocs.io/en/latest/BOOK.html which 404s

![screen shot 2017-10-04 at 21 53 29](https://user-images.githubusercontent.com/371796/31211469-13710bbc-a94e-11e7-86b5-1e3e8861944b.png)

**Comment by zehicle** [comment]
fixed - updated links a while back.  forgot to close issue
