### ISSUE TITLE
Updated Plugin Model 

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#476]
Updated Plugin Model

**Comment by sygibson** [comment]
Part of terraform work revealed some existing Hashicorp plugin library sets that are much further along with testing and usage in the field.   The goal is to move over to using the Hashicorp library for plugin management. 

https://github.com/hashicorp/go-plugin 

Largest feature we look forward to taking advantage of is to enable bi-directional capabilities.  Useful for extending APIs, generating direct API calls, etc...

**Comment by galthaus** [comment]
Fix in tip.
