### ISSUE TITLE
Default Stage Transition

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#477]
Default Stage Transition

**Comment by sygibson** [comment]
Noticed trend for every stage to include "change stage" task.  Causes some technical issues causing dangling jobs to be open. 

Believe best solution is to check the map and transition as appropriate.  

Reboot flag on stage now becomes meaningful.   

Additional stage added called "noop" or "none".

**Comment by galthaus** [comment]
Reviewing the default content to see what should be merged with rackN content to simplify the content layers.

**Comment by zehicle** [comment]
@sygibson please review and see if this has been addressed.

**Comment by sygibson** [comment]
completed - in v3.5.0
