### ISSUE TITLE
machine inventory

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#478]
machine inventory

**Comment by sygibson** [comment]
Inventory system - shadowing the Ohai solution from OpsCode that does machine information inventory. 

RackN is working on a gohai (Go implementation of Ohai) which will enable similar Inventory collection abilities to the Ohai solution.  There are some missing elements in Ohai.  These will be added to the new gohai solution (eg Disks and Partitioning), and community requests for GPUs inventory information. 

Currently the gohai inventory system is in closed Github RackN repo, this will be released in the future (likely) as Registered content/capability.   Details on that forthcoming. 

gohai will be embedded in Sledgehammer

**Comment by VictorLowther** [comment]
Gohai is in the current version of Sledgehammer and there is a basic inventory task in the os-discovery workload that performs basic system inventory.

**Comment by galthaus** [comment]
Coming:
Disk Inventory
GPU Inventory

**Comment by zehicle** [comment]
can we market this as complete and open new issues for added features?

**Comment by zehicle** [comment]
completed
