### ISSUE TITLE
Template Clone hangs but works.

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/provision#504]
wdennis [11:12 PM] 
I select the stock template, click “Clone”, then change the ID and Contents, but when I click “Add”, it never returns…

[11:13] 
If I do a browser refresh, it seems that it had worked, the new template is there with the “unlocked” icon

**Comment by zehicle** [comment]
this is a common issue on several save pages - they do not close the view correctly.  @Meshiest

**Comment by zehicle** [comment]
fixed
