### ISSUE TITLE
UX: after logging in to Portal account, locked icons still remain

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#513]
log in to RackN Portal account
locked icons (eg workflow, stages, etc) still show content is locked
hard refresh browser - still shows locked
click on a "locked" item (eg "workflow"), results in lock icon being removed from all locked items

Essentially - the content/features are no longer locked, but the UX still shows them locked until you try to access a given feature.

Expectation - after log in to RackN Portal account, unlocked content/features should no longer show a lock icon.

**Comment by galthaus** [comment]
This is not working for me.

I do this:
1. open a logged out new browser.
2. https://127.0.0.1:8092/
3. See the locked icons.
4. Click login in right corner and login.
5. Lock icons still there.
6. Click somewhere in NAV and see lock icons go away

**Comment by galthaus** [comment]
This is fixed now.
