### ISSUE TITLE
"upgrade all" for content packages

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#514]
Currently if I have multiple content packages that have upgrades available, I have to select each individually to upgrade them.  

It would be fabulous if there was an "upgrade all" button that iterates through each content package and upgrades it if there is an upgrade available.

**Comment by zehicle** [comment]
New UX feature to audit versions allows quick view of what's out of date.
Actual will be harder

**Comment by sygibson** [comment]
progress with content versions via api and UX comparison

**Comment by zehicle** [comment]
this was added.

**Comment by galthaus** [comment]
Verified
