### ISSUE TITLE
How to run dr-provision with existing DHCP server

### ISSUE THREAD

**Issue by rothgar** [digitalrebar/provision#532]
It should be documented how to run `dr-provision` with an existing DHCP server. Ideally dnsmasq can be used as a proxy dhcp server to enable option 66/67 for booting. Here's an example from the CoreOS matchbox documentation.
```
docker run --rm --cap-add=NET_ADMIN --net=host --name=dnsmasq quay.io/coreos/dnsmasq \                                                          
  -d -q --dhcp-range=192.168.86.1,proxy,255.255.255.0 \
  --enable-tftp --tftp-root=/var/lib/tftpboot \
  --dhcp-userclass='set:ipxe,iPXE' \
  --pxe-service='tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe' \
  --pxe-service='tag:ipxe,x86PC,"iPXE",http://matchbox.lan:8080/boot.ipxe' \
  --log-queries \
  --log-dhcp
```
I'm sure I can use the similar options for dr-provision but I don't know the ipxe endpoint for `dr-provision`. It'd be great if this were documented to run externally or enable it with a flag.

**Comment by galthaus** [comment]
Missed the word, proxy.  For my clarity, you are using a DHCP server that doesn't return booting options and you want another DHCP server to respond with the boot options in proxy mode.  Augmenting the data of the primary DHCP server.  Proxy mode is an interesting feature request for DRP.  That way another process wouldn't be need for this simple process.

**Comment by rothgar** [comment]
Yes exactly. Right now I'm trying dr-provision in my home environment where DHCP is handled by my router. I don't want to turn off DHCP on the router just to test PXE booting my lab.
Even in a work environment it's likely organizations already have DHCP servers that are highly configurable or highly available. Letting dr-provision work in proxy mode would ease the integration in existing environments.

**Comment by rothgar** [comment]
Any chance you could provide an example dnsmasq configuration that would work as a proxy for drp?

It be great if an image were provided or sending configuration to coreos' provided image is also an option.

I'm assuming changing the ipxe endpoint may be good enough. Something like this may work (needs testing)
```
docker run --rm --cap-add=NET_ADMIN --net=host --name=dnsmasq quay.io/coreos/dnsmasq \                                                          
  -d -q --dhcp-range=192.168.86.1,proxy,255.255.255.0 \
  --enable-tftp --tftp-root=/var/lib/tftpboot \
  --dhcp-userclass='set:ipxe,iPXE' \
  --pxe-service='tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe' \
  --pxe-service='tag:ipxe,x86PC,"iPXE",http://DRP_IP:8091/default.ipxe' \
  --log-queries \
  --log-dhcp
```

**Comment by galthaus** [comment]
While I'm unsure of the mechanism that Packet.net is using, this is how DRP provisions packet.net servers.  You have the node boot an ipxe image and have `http://DRP_IP:8091/default.ipxe` as the ipxe config file.  I'm not sure what they are doing to get the initial ipxe image there.  We do have DRP server ipxe.pxe as an ipxe boot loader and it might now to get default.ipxe from where it got the ipxe.pxe image.  I haven't tried that in a while if ever.

**Comment by rothgar** [comment]
To follow up on this, the above command didn't work. Looking at the default.ipxe image it looks like it points back to tftp
```
#!ipxe
chain tftp://192.168.86.7/${netX/ip}.ipxe || exit
```
That was causing a port conflict between dnsmasq and DRP.

I got dnsmasq working in proxy mode pointed to my DRP with this
```
docker run --rm --cap-add=NET_ADMIN --net=host --name=dnsmasq -t quay.io/coreos/dnsmasq \
  -d -q \
  --dhcp-range=192.168.86.1,proxy,255.255.255.0 \
  --dhcp-option=66,"$DRP_IP" \
  --log-dhcp
```
I'm going to test more tomorrow night. If that works we can close this issue.

**Comment by galthaus** [comment]
Hmmm - I wonder about that.  I bet we could change it from tftp to http.

**Comment by galthaus** [comment]
Okay - what is funny or not is that one of the default-ipxe files uses http.  The ones directly contained in the bootenvs don't.  I'm going to change that so it is easier.

**Comment by rothgar** [comment]
That would be great to stay on http. tftp is very slow and hard to scale from my experience.

Were you able to replicate my dnsmasq flags to see if it works as a proxy dhcp server offering option 66?

**Comment by galthaus** [comment]
I haven't.  I would need to create an environment for that.  Need to think about how and where to do that.

**Comment by rothgar** [comment]
It's OK, I'll verify tonight when I'm back home and it's not midnight

**Comment by rothgar** [comment]
Well I can confirm this didn't work. Multiple problems here. One is the fact that I forgot to set a filename with option 67. I'm guessing DRP provides pxelinux.0 but I'm not sure.

The other problem is some of my hosts are using UEFI and others are using standard PXEClient.
Example logs from dnsmasq
```
dnsmasq-dhcp: 693869348 vendor class: PXEClient:Arch:00007:UNDI:003016
dnsmasq-dhcp: 755875946 vendor class: PXEClient:Arch:00000:UNDI:002001
```

I'll need to figure something else out.

**Comment by galthaus** [comment]
Yes, we provide lpxelinux.0 for now iPXE enabled devices.

Hmm - well, we can handle this in our DHCP server.  For Option 67, you can do something like this:

'{{if (eq (index . 77) "iPXE") }}default.ipxe{{else if (eq (index . 93) "0")}}lpxelinux.0{{else}}bootx64.efi{{end}}'

This will test option 77 for iPXE and send 'default.ipxe'.  Otherwise, it will test 93 for 0, which is "legacy" and send lpxelinux.0.  And finally, it will send and EFI network boot loader last.  This way "all" the cases are covered.

**Comment by zehicle** [comment]
@rothgar can you review and check?  We are considering this closed

**Comment by sygibson** [comment]
closing due to internal and other community members validating it functions

@rothgar  please re-open if you see this issue again
