### ISSUE TITLE
Quickstart install.sh fails on fedora

### ISSUE THREAD

**Issue by rothgar** [digitalrebar/provision#533]
The `install.sh` script fails on fedora if p7zip isn't already installed because it tries to install epel-release which isn't a package available on fedora.

If fedora isn't supported feel free to close this ticket. If it is supported then there should be an exclusion in the script to not install epel-release. The p7zip package is available in the standard fedora repo.

**Comment by galthaus** [comment]
We didn't explicitly exclude fedora, but it sounds like we need to tweak it a little.  :-)
