### ISSUE TITLE
Allow DRP to restrict its TLS cyphers

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/provision#562]
In order to reduce the risk in TLS compromise by using medium strength cyphers, add a flag that will change allow the use of medium cyphers if there is an issue with clients.  The default cypher set should remove the CBC-based cyphers.

This will add the `--old-cyphers` to reset the original values.

**Comment by galthaus** [comment]
The flag is `--use-old-ciphers`

**Comment by zehicle** [comment]
fixed
