### ISSUE TITLE
Cloning BootEnv throws error in UX

### ISSUE THREAD

**Issue by wdennis** [digitalrebar/provision#570]
A clone of a BootEnv thru UX throws Template errors when trying to save
error pic [here](https://rackn.slack.com/files/U416T0AAX/F86NJD11P/bootenv-clone-fail-ux.png)

@sygibson verified bug on his system

**Comment by zehicle** [comment]
this is helpful.  thank you.

**Comment by zehicle** [comment]
update - this is NOT a clone problem.  I believe it would impact new bootenvs too.

**Comment by zehicle** [comment]
There is a fix for RackN code in review... was a generic problem, not specific to bootenvs but likely only impacts this one usecase.

**Comment by zehicle** [comment]
This is fixed.
