### ISSUE TITLE
Error http://mirrors.kernel.org/centos/7.3.1611/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso

### ISSUE THREAD

**Issue by nguyenhappy92** [digitalrebar/provision#576]
Dear all,
When i running command line curl -fsSL https://raw.githubusercontent.com/digitalrebar/digitalrebar/master/deploy/quickstart.sh | bash, This is apearing error http://mirrors.kernel.org/centos/7.3.1611/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso
![image](https://user-images.githubusercontent.com/8796104/33545938-3c237312-d912-11e7-817c-19859bd7dae9.png)
Please help me it. I have found this issue on Google and home rebar but cann't solve
Thank you !

**Comment by sygibson** [comment]
@nguyenhappy92 - The CentOS team has completely removed the CentOS 7.3.1611 ISO distribution from all mirrors.  This is not an issue related to Digital Rebar Provision. 

Please update your version of Digital Rebar Provision to the current `stable` version - as it contains updates in our CentOS content pack to use the current CentOS 7.4.1708.  

You can find details on the upgrade/updating procedures at: 

  [Digital Rebar Provision: Upgrade Documentation](http://provision.readthedocs.io/en/latest/doc/upgrade.html) 

The Ubuntu 16.04 BootEnv content pack in your current version of DRP should still work fine.  However, we do recommend upgrading if you can - as there are several significant fixes and enhancements in the new version of DRP from the version you have. 

If you have not yet developed any specific configuration or content in your current version - it is highly recommended that you simply perform a fresh install of the DRP Endpoint - after you completely remove the old version. 

Please feel free to join our [Slack #community](http://www.rackn.com/support/slack/) channel for community based best-effort support if you need any further help or information.  

Please note I am closing this issue as it is not related to a bug or defect in Digital Rebar Provision.

Thank you.

**Comment by sygibson** [comment]
Also - our Quickstart guide contains updated documentation on installing Digital Rebar Provision, you can find it at:

  [Digital Rebar Provision: Quickstart](http://provision.readthedocs.io/en/latest/doc/quickstart.html)

**Comment by nguyenhappy92** [comment]
@sygibson 
I have install with guide at http://provision.readthedocs.io/en/latest/doc/quickstart.html but I have met appear error after install command line curl -fsSL get.rebar.digital/stable | bash -s -- install --isolated then run next command line ./drpcli bootenvs uploadiso centos-7-install
![image](https://user-images.githubusercontent.com/8796104/33585144-5dc294d4-d995-11e7-9ea5-4958024d23f1.png)
Please give me advice and resolve this issue.
Thank you !

**Comment by sygibson** [comment]
Please join Slack and we can help you in the #community channel.   

http://www.rackn.com/support/slack/

**Comment by galthaus** [comment]
You need to make sure you have started `dr-provision`.  There is a line in the output that reads like this:

sudo ./dr-provision --static-ip=<SOME IP ADDRESS> --file-root=`pwd`/drp-data/tftpboot --data-root=drp-data/digitalrebar --local-store=\"\" --default-store=\"\" 

Do what @sygibson says and look for that line.
