### ISSUE TITLE
machine name beginning w/ number breaks provisioning

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#597]
Currently we do not allow machine names to begin with a number.  RFC1123 says it may contain a number first, but *might* break things - however it's not strictly forbidden. 

I believe we need to allow number to start machine name. 

This caused lab training at Juniper to fail because I created machine names w/ 5min- prefix.

**Comment by galthaus** [comment]
This was an "enhancement" for 3.4.0 when we started validating names across the board.   A good thing.  Maybe too restrictive in this latest pass.

**Comment by zehicle** [comment]
I believe this can be closed.

**Comment by galthaus** [comment]
No this is not fixed.  Machines as of 75738d5e8fc0bb96cda4fdf53be0d6cfcb287df3 must have a letter to start.

**Comment by sygibson** [comment]
needs fixed

**Comment by galthaus** [comment]
It was fixed on May 24.
