### ISSUE TITLE
Contents - need helper for drpcli based Content installs

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#615]
(Probably also needed for Plugin Providers as well)

Currently the method to install content is relatively tedious ...  At a minimum, requiring:

```
curl -s https://qww9e4paf1.execute-api.us-west-2.amazonaws.com/main/catalog/content/krib -o krib.json
drpcli contents create -< krib.json
```

We should think of a solution to ease referencing content both via API and CLI such that it can become a single (Authentication requirements not withstanding) call to get a specific contents pack and version.

Use the Content "ID" field name:

  krib
  ipmi-packet
  ipmi

Install should then be as simple as `drpcli contents install ipmi-packet`.  

An optional trailing argument could be `stable`, `tip`, `1.4.0` ... etc to specify version of content to get/install.

**Comment by zehicle** [comment]
I think drpcli contents bundle and upload addresses

**Comment by galthaus** [comment]
This is really about getting content packs from the SaaS Portal through the CLI.

**Comment by sygibson** [comment]
* completed - released as `catalog:` keyword w/ the Catalog support in v3.13.0
example:  `drpcli contents upload catalog:task-library-stable`
