### ISSUE TITLE
UX: add "Raw JSON" option to right side pop-out panels

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#616]
Similar to the **Clone** feature, add a right side pop-out panel option to show Raw JSON of the object being manipulated. 

Example - Profiles - "global", should be able to show/view the raw JSON - no the parsed and presented view only.

**Comment by zehicle** [comment]
interesting idea.

**Comment by galthaus** [comment]
sigh - with color

**Comment by galthaus** [comment]
Done.  In tip and test at 4:00p CST 2/19
