### ISSUE TITLE
`drpcli machines stage ...` change fails to change stage

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#617]
Machine is sitting completed in "complete-nowait" stage - no tasks in the queue.   Try to change stage with the DRPCLI command fails (bootenv/stage both exist and are good):

`drpcli machines stage bff5513f-7f63-43c6-b744-5eefaa9716be centos-7-install`

Error: PATCH: machines/bff5513f-7f63-43c6-b744-5eefaa9716be
  Patch error: Test op failed.
  Patch line:
{
  "op": "test",
  "path": "",
  "from": "",
  "value": {
    "Address": "147.75.64.43",
    "Available": true,
    "BootEnv": "local",
    "CurrentJob": "54c8230e-b8bd-42c4-8ac1-7647003566f4",
    "CurrentTask": 0,
    "Description": "",
    "Errors": [],
    "Meta": {
      "feature-flags": "change-stage-v2"
    },
    "Name": "pkt5min-nodes-ewr1-01.unspecified.domain.local",
    "OS": "ubuntu-16.04",
    "Params": null,
    "Profile": {
      "Available": false,
      "Description": "",
      "Errors": [],
      "Meta": {},
      "Name": "",
      "Params": {
        "gohai-inventory": {
          "snip": "snip"
        },
        "packet/uuid": "aaecc4fd-5d59-47fb-b840-35138c099d8b"
      },
      "ReadOnly": false,
      "Validated": false
    },
    "Profiles": [
      "packet-console",
      "my-k8s-cluster"
    ],
    "ReadOnly": false,
    "Runnable": true,
    "Secret": "Ef8HRmgmpwO7fTSv",
    "Stage": "complete-nowait",
    "Tasks": [],
    "Uuid": "bff5513f-7f63-43c6-b744-5eefaa9716be",
    "Validated": true
  }
}
```

**Comment by galthaus** [comment]
happens in v3.4.0 and v3.6.0, but not v3.2.1.

**Comment by lae** [comment]
This appears to be resolved for me on tip.
