### ISSUE TITLE
plugin_provider content not installed correctly

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#636]
I bumped in to a logging problem that needs to be addressed ... here's what happened:
* customer installed plugin-provider packet
* instantiated the plugin w/ UI **add plugin** 
* created workflow (to install centos-7), booted packet machine
* it stopped in _discover_ stage w/ _success_ exit
* it never advanced to _packet-discover_
* on the machine **journalctl -u sledgehammer** showed:
```
Jan 12 19:12:09 riot-machines-ewr1-02.unspecified.domain.local sledgehammer-starr
t-up.sh[1333]: Error: GET: stages/packet-discover: Not Found
```

It looks like somehow, the actual _packet-discover_ stage and other content did not get installed correctly when the provider was installed.  I don't see anything in the standard log messages related to errors, or any **delete** by customer.  Logs show the **plugin_provider** was initially installed with a success exit.

Deleted the provider, and re-added it, then everything was fine .... 

PROBLEM:  the stage failure was never bubbled up in the **jobs** logs - it marked _discover_ as successful and the transition to _packet-discover_ had failed.

**Comment by galthaus** [comment]
I think this is fixed by plugin-v2
