### ISSUE TITLE
UX: add warning flag/icon if "prefs" relies on missing BootEnv/Stage

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#661]
In the UX - the Info & Preferences screen renders the:

defaultBootenv
defaultStage
unknownBootenv 

If the BootEnv or Stage are set correctly, but missing, the UX renders "-" for the settings.  This enhancement ask is to add a "Flag" or warning "Icon" or text of some sort that specifies 

"BootEnv/Stage" error: missing bootenv sledgehammer

or similar to the user.

**Comment by sygibson** [comment]
Currently the UX renders this situation like: 

![screen shot 2018-01-26 at 07 40 35](https://user-images.githubusercontent.com/5308433/35448003-f5799f2e-026d-11e8-94ec-a3ca87fface2.png)

A possible "mock-up" might look like this: 

![screen shot 2018-01-26 at 07 40 35](https://user-images.githubusercontent.com/5308433/35448331-ce4a76c0-026e-11e8-9683-b6cb7c689ea1.png)

With appropriate Hover-over error text assigned to the icon.

**Comment by sygibson** [comment]
ah!   FontAwesome icon "warning" - rendered either red or yellow.

**Comment by zehicle** [comment]
Fixed - I added a HUGE WARNING BOX for this with specifics about which items are not available.

**Comment by galthaus** [comment]
Verified
