### ISSUE TITLE
UX: delete all jobs button

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#677]
When playing around with building up a DRP endpoint, I often want to wipe the jobs logs to remove all the extraneous logs.  Yes, I can simply nuke them from the jobs directory on the filesystem .... 

In the UX - I'd like to see the Jobs menu item have a "Delete All" button that wipes all jobs.

**Comment by sygibson** [comment]
When I have a large number of jobs - and select "All" for show jobs per page - then select all - and delete - it causes a huge hang/delay on the UX as it tries to individually delete all of the jobs. 

If "delete all jobs" can be asynchronous ... that'd be a lot better ...

**Comment by galthaus** [comment]
Yeah - this is strange and more based upon the api.  Need to think about this.

**Comment by galthaus** [comment]
This now works async and all jobs in view are removed.  It is probably better enough.
