### ISSUE TITLE
UX: add Jobs logs to machines in Bulk Actions/Machines

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#678]
In both the Machines and Bulk Actions panels - it would be nice to have an icon that clicks through to Jobs w/ the Machine UUID filter applied - so you can quickly view jobs related to a given Machine UUID from these screens.

**Comment by zehicle** [comment]
![image](https://user-images.githubusercontent.com/724948/35839690-5f29f526-0ab7-11e8-9c53-a718c7839a0f.png)

**Comment by zehicle** [comment]
This is coded in a way that we can easily add more links to other pages.

**Comment by galthaus** [comment]
This doesn't apply the filter.  The link is good, but part of this was to preset the filter based upon the selected machines to reduce the size of the jobs list.

**Comment by galthaus** [comment]
The filter also only works on one machine.

**Comment by sygibson** [comment]
still more work needed here

**Comment by zehicle** [comment]
added in v3.11 release
