### ISSUE TITLE
UX: jobs filters has no "save" or "submit"

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#679]
It appears going to the Jobs --> Filters panel - there is no "way out".  There appears to be no "save" or "submit" after specifying new filters.  The pop-out panel also prevents clicking off the panel to dismiss it.   The "X" dismiss is rendered over the top of the upper right-most control slider (Jobs Filters / Reverse).

Tested Chrome, Firefox, and Safari browsers.

**Comment by sygibson** [comment]
This also applies to the Bulk Actions --> Filters panel pop-out as well.  

Presumably any other place we call the Filter panel this is present.

**Comment by galthaus** [comment]
This is a usage thing.  There is not a save.  You set the values in the form and click the x.  That applies it.  The filter is not persisted.  It is for current view and gets reset if the page is left.  It appears that the x is always there, but is rendered not in the same line as the reverse.

**Comment by galthaus** [comment]
Not sure what to do about this.  This is working as designed, but designed poorly.

**Comment by sygibson** [comment]
"X" to me means "dismiss" / "delete" / "destroy" ... or "cancel" 

From a UI perspective, I'd like to see:

  "X" = "Cancel" - do not apply the filters to this page
  "✓" = "Apply" - set these filters for this page

Note the current "X" also overflows/over-writes the top right filter text, so some CSS-ery needs to be applied to keep the "X" and "✓" in a consistent place that doesn't overflow the filters.

**Comment by galthaus** [comment]
Done.  Apply and Cancel buttons that do the right thing are now available.
