### ISSUE TITLE
UX: workflow overflows to the right for long workflow chains

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#680]
Currently - if you have 5 or more stages in a given workflow, the UX screen renders it as an overflow to the panel edge, off to the right.   I suggest "breaking" the workflow up in to multi-line using ellipsis at end and beginning of the breaks.  See the attached image for a mock up reference. 

It also would be nice to add a darker horizontal rule if possible between each workflow item, to help differentiate them as separate workflows (also rendered in the mockup). 

![ux - fix workflow mockup screen](https://user-images.githubusercontent.com/5308433/35653232-026080f4-069c-11e8-945e-67e16ef6d798.png)

**Comment by sygibson** [comment]
An alternate, though probably rob-disapproved ... visual add might be one of the two following options:

Subtle green begin and red end bars:

![ux - fix workflow mockup screen - green and red end bars](https://user-images.githubusercontent.com/5308433/35653416-fd9e01a8-069c-11e8-9cb4-265938eba12b.png)

Or even more rob-disapproved, full green/red begin/end bars:

![ux - fix workflow mockup screen - green and red full stages](https://user-images.githubusercontent.com/5308433/35653428-0f99534e-069d-11e8-8a12-061304f8713e.png)

**Comment by sygibson** [comment]
(and yes, I know the "continued workflow" example I mocked up isn't exactly right as far as a workflow goes ... :) )

**Comment by zehicle** [comment]
would having a "compact" mode work?

**Comment by zehicle** [comment]
Make the lists smaller - workaround.
