### ISSUE TITLE
UX:  bulk actions, subsequent selections fail

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#682]
in the bulk actions panel, if you select N machines, apply an action - the action is applied successfully, those N machines remain selected, then you apply another action - the action will result in failure

if you deselect each Machine, and then reselect the Machine again - and apply the same failed action, the action results in success 

It appears that attempting to apply multiple actions in sequence will fail - UNLESS you deselect the Machine, then reselect the machine

**Comment by galthaus** [comment]
I did the following:
1. create empty profile aa
2. go to bulk actions screen
3. select all machines.
4. add aa to all machines.
I found that sometimes the UX doesn't refresh.  Most of the time the icons in the list refresh.  Regardless.
5. Immediately remove the profile by clicking the -.
This fails with patch error.
6. click the all selected check box twice to deselect and reselect all machines.
7. remove the profile
8 success.
9. immediately add the profile by the clicking the +.
10. fails!
11. deselect/reselect
12. add the profile 
13. success

**Comment by zehicle** [comment]
I have replicated - reviewing

**Comment by zehicle** [comment]
Fix submitted https://github.com/rackn/provision-ux/pull/349
