### ISSUE TITLE
Windows Binaries do not have `exe` extension

### ISSUE THREAD

**Issue by cdhunt** [digitalrebar/provision#688]
Otherwise, they appear to be valid windows binaries. 

Breaking up the release binaries by platform would probably be a welcome change as well.

**Comment by galthaus** [comment]
As a linux guy, is the exe required or just helpful.  I can add it.

**Comment by cdhunt** [comment]
It is required for us Windows folks or Windows assumes it's text.

**Comment by galthaus** [comment]
Wow - didn't want auto close.  It isn't quite out in the tree as tip binaries yet.

**Comment by galthaus** [comment]
This is now in tip.  windows exes have .exe for drp at least.  Other plugins won't for the moment, but that is a different tree.
