### ISSUE TITLE
Can't start dr-provision.exe on Windows

### ISSUE THREAD

**Issue by cdhunt** [digitalrebar/provision#689]
All of the default values are Linux centric.

I tried to pass a Windows file path and received an error.

```powershell
PS C:\dr-provision\bin\windows\amd64> .\dr-provision.exe /base-root c:\drp
dr-provision2018/02/02 20:14:04.155037 Version: v3.6.0-tip-96-60f590b26317f3736767b097ffbbcbd96e868845
dr-provision2018/02/02 20:14:04.160055 Extracting Default Assets
dr-provision2018/02/02 20:14:04.849551 Unable to create DataStack: Failed to open backend content (directory://c:\drp\di
gitalrebar): parse directory://c:\drp\digitalrebar: invalid character "\\" in host name
```

Do you have an example command line for starting Srovision on Windows?

**Comment by galthaus** [comment]
@cdhunt - wow!  This is awesome.  We in general expect DRP to run on linux or mac but be able to provision windows.  I suspect our path logic need a little more help.  Let me look at it and see.

**Comment by cdhunt** [comment]
FWIW: it did do something.

```
PS C:\dr-provision\bin\windows\amd64> tree c:\drp
Folder PATH listing
Volume serial number is 580A-8CF3
C:\DRP
├───digitalrebar
├───job-logs
├───plugins
├───replace
├───saas-content
├───tftpboot
│   ├───files
│   ├───isos
│   ├───machines
│   └───pxelinux.cfg
├───ux
└───var
    └───run
```

**Comment by galthaus** [comment]
This is a bug on our side.  I looking at it now.

**Comment by galthaus** [comment]
This should be fixed as well.

**Comment by cdhunt** [comment]
Thanks. Dealing with the embedded assets is going to be a bit of a hurdle.

**Comment by galthaus** [comment]
Yeah - drpcli is really the thing we are targeting for windows.  I shouldn't have closed this.  I misread it.

**Comment by cdhunt** [comment]
I'm having trouble generating assets even on Linux. Would you be able to publish new binaries? I'll test running it on Windows.

**Comment by galthaus** [comment]
The tip release in GitHub should have all the binaries for what you want.

**Comment by sygibson** [comment]
drpcli now runs on windows
dr-provision does not - and probably won't - some golang library issues exist that make this extremely hard to support on windows...

**Comment by galthaus** [comment]
We are not going to make dr-provision run on Windows at the current moment.  drpcli and bundler does.  Running in a container or VM on windows would be the preferred method.
