### ISSUE TITLE
UX: use-case - view differences between two versions of content

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#702]
As a user of the UX - I would like to be able to view the difference between two versions of Content Packs.

For example - the UX Contents panel tells me that "drp-community-content" has updates from v1.5.0 to v1.6.0.  I would like to be able to view the difference between the two versions to determine whether I wanted to update, or what the update would specifically effect. 

For this use case - I believe the difference between the two JSON pieces is sufficient, and it is not necessary to roll this up under the drop down selectors for each resource type (eg Profiles, Params, etc.)

**Comment by galthaus** [comment]
now in tip and test or will be in at about 4:00p CST 2/19
