### ISSUE TITLE
UX: adding Param of type array provides incorrect "{}" in input box

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#704]
On a profile, machine, etc... if you try to add an Array type Param, the UX will give you an input box to enter the values for the Array, as follows:

![screen shot 2018-02-10 at 13 23 51](https://user-images.githubusercontent.com/5308433/36066819-d2c3f246-0e65-11e8-82bc-0b14894f33f2.png)

This leads someone unfamiliar with JSON syntax to try and input a value like: 

   `{ "0.us.pool.ntp" }`

The correct syntax is:

   `[ "0.us.pool.ntp" ]`

When inputting the INCORRECT curly brace syntax ( "{}" ) - there are NO warnings provided that incorrect Param type was used, and the values input will just be swallowed and chucked out. 

The UX should pre-populate the input box with the correct square brackets for Array type objects.

**Comment by galthaus** [comment]
resolved by ux 335
