### ISSUE TITLE
Offline commands shouldn't attempt to connect to DRP

### ISSUE THREAD

**Issue by lae** [digitalrebar/provision#705]
For some commands, I don't expect them to require a network connection to complete. When I ran the following command, it hung while DRP's API was hanging (not sure why yet), so I stopped DRP and saw that it was attempting to connect before executing:
```
[lae@yuzu fireeye-content]$ drpcli contents bundle
2018/02/12 17:35:25 Error creating session: CLIENT_ERROR: Get https://fqdn:8092/api/v3/users/lae/token: dial tcp ip:8092: getsockopt: connection refused
```
Could we have this (and any others if relevant) not require a session to execute?

**Comment by galthaus** [comment]
I think the commands are:
version
autocomplete
contents bundle
contents unbundle
gohai

gohai is a client side command that only really runs in sledgehammer.
version and autocomplete already do this.

contents bundle/unbundle are the remaining ones.  We already have drbundler which is a different contents bundle that works offline.  We don't ship it in the zip.

**Comment by galthaus** [comment]
Will be in tip shortly.
