### ISSUE TITLE
UX: adding Params of type Boolean in test/latest/rackn.github.io UX endpoint fails

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#722]
Setting Boolean type Params on Machines fails.

Observed as follows:
on test/latest/rackn.github.io - but not on stable/portal

When no Params exist, do:
1. go to machine
2. edit machine
3. add Param (used "local-repo" as example)
4. select Save

Get Error
Patch error at line 0: Selector local-repo not a member of map[string]interface {}{"gohai-inventory" <...snip...> , Patch line: {"op":"test","path":"/Params/local-repo","from":"","value":{}}

error:
![screen shot 2018-02-14 at 15 55 22](https://user-images.githubusercontent.com/5308433/36234722-78b2ccc0-11a1-11e8-9a82-2b55e23afb0b.png)

The error does not appear to occur for String, Array, or Object type Params.

Once the error occurs, if you review the Machine info again - you'll see the Boolean Param has been added, but has not been added with a true/false value:

![screen shot 2018-02-14 at 16 00 05](https://user-images.githubusercontent.com/5308433/36234783-d7e256b6-11a1-11e8-874f-7356be90ca1e.png)

REMOVING a Boolean Param results in similar behavior - error message, however, it appears to actually remove the Param.

PATCH error 409 occurs in developer tools:

{"Model":"machines","Key":"ebc1c6db-9eca-4d16-bd8c-cc868cd6d632","Type":"PATCH","Messages":["Patch error at line 0: Test op failed.","Patch line: {\"op\":\"test\",\"path\":\"/Params/local-repo\",\"from\":\"\",\"value\":{}}"],"Code":409}

**Comment by galthaus** [comment]
Should be fixed in the latest ux.
