### ISSUE TITLE
UX: UX and DR version info line wraps ugly

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#723]
If UX horizontal width is too narrow, the ugly red banner for DR and UX version info line wraps, causing overflow of the wrapped text.

![screen shot 2018-02-14 at 16 34 09](https://user-images.githubusercontent.com/5308433/36235363-f8c6a7bc-11a4-11e8-982d-92ae4e9a9801.png)

![screen shot 2018-02-14 at 16 36 38](https://user-images.githubusercontent.com/5308433/36235409-413ab8bc-11a5-11e8-9630-06afe34b840b.png)

Really ...  please mute the red somewhat in the warning banner ... :)

**Comment by zehicle** [comment]
Fixed.  Color of the ribbon can be set from the Application Session Storage by adding "alertColor" and assigning a value.  I recommend "purple" for @sygibson
