### ISSUE TITLE
UX:  "system wizard" dismissed creates dead linke for "Done!"

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#732]
If the System Wizard is marked "completed" ... the wizard panel shows a URL Link with the target name "Done!", which goes to a dead link of "Undefined". 

Example:
https://rackn.github.io/provision-ux/#/e/147.75.65.3:8092/undefined 

![screen shot 2018-02-19 at 15 10 23](https://user-images.githubusercontent.com/5308433/36400712-9ab9bd30-1587-11e8-9ed0-d65585f09db3.png)

renders to page:

![screen shot 2018-02-19 at 15 10 33](https://user-images.githubusercontent.com/5308433/36400715-a1ae00c4-1587-11e8-9643-22443730ccd6.png)

**Comment by galthaus** [comment]
Fixed
