### ISSUE TITLE
pxe-t04 access violation

### ISSUE THREAD

**Issue by amit-handa** [digitalrebar/provision#738]
Hi,
I am a newbie in devops world. Evaluating 'provision' to devops the SOHO server infrastructure, we have.
I want to pxe boot/install/test with virtualbox VMs before moving on to actual servers.
I installed virtualbox, created a VM, configured it to pxe boot.

started dr-provision, as follows
```
 sudo dr-provision --log-level=debug --debug-dhcp=debug --debug-bootenv=debug --dhcp-ifs=wlan0
```

On pxe booting, dhcp is assigned correctly. however, tftp issues following error
**pxe-t04 access violation**

please note that I am testing corporate environment. there is already a DHCP server running.
However, the VM pxe-boot info shows that it is picking up 'provision' dhcp server.
Logs of dr-provision and scanshot of virtualbox VM is **attached**, for reference.

Would love to know how can I move forward with my endeavour. Also, is there a community to whom I can throw these queries ?

Thanks,
![virtualbox](https://user-images.githubusercontent.com/7656227/36465583-cfc2a74c-16fb-11e8-98d7-dc5c8c8ae714.png)
[drp.log](https://github.com/digitalrebar/provision/files/1743008/drp.log)

**Comment by amit-handa** [comment]
another thing is that dhcp is shown as not 'alive'. If it would help.

```
 drpcli info status
{
  "API": {
    "Alive": true,
    "Enabled": true,
    "Port": 8092
  },
  "BINL": {
    "Alive": false,
    "Enabled": true,
    "Port": 4011
  },
  "DHCP": {
    "Alive": false,
    "Enabled": true,
    "Port": 67
  },
  "Static": {
    "Alive": true,
    "Enabled": true,
    "Port": 8091
  },
  "TFTP": {
    "Alive": true,
    "Enabled": true,
    "Port": 69
  }
}
```

**Comment by amit-handa** [comment]
experiment 2:
disconnected laptop from corporate network.
restarted provision server and VM.

``` drpcli info status ```
correctly shows the dhcp server as 'alive'

when the VM pxe-boots, dhcp is correctly assigned. however, while downloading lpxelinux.0. It shows following error:
server:
dr-provision2018/02/21 06:50:20.509199 [0:195]static [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/midlayer/tftp.go:47
[0:195]TFTP: attempting to send lpxelinux.0
dr-provision2018/02/21 06:50:20.509271 [0:196]static [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/midlayer/tftp.go:64
[0:196]TFTP: lpxelinux.0: size: 91550
dr-provision2018/02/21 06:50:22.533358 [0:197]static [error]: /home/travis/gopath/src/github.com/digitalrebar/provision/midlayer/tftp.go:68
[0:197]TFTP: lpxelinux.0: transfer error: read udp [::]:55270: i/o timeout

VM:
PXE-E32: TFTP open timeout

please help.

**Comment by galthaus** [comment]
There is a community: https://github.com/digitalrebar/provision#community-resources

Make sure to check your firewall to ensure that it is either off or that you are not restricting ports 67. 68. 69, 8091, 8092, 4011 tcp/udp.

**Comment by VictorLowther** [comment]
Is that vbox VM configured to run in legacy BIOS mode or UEFI mode?

**Comment by amit-handa** [comment]
Thanks. I have joined the slack community.
@VictorLowther the issue was observed in company. After I have come back home, it has successfully booted sledgehammer bootenv.
I ll dig in more to see if I am able to reproduce the issue and get back.
Thanks alot for your kind response.

**Comment by VictorLowther** [comment]
ok 

FWIW, the transfer error you saw is generally harmless -- it is  usually the fnic irmware starting a TFTP download to get the size of a file and then aborting the transfer once it has the size.  As long as the systems are actually PXE booting you can ignore that error.

**Comment by amit-handa** [comment]
update: I am receiving **pxe-e32: tftp open timeout**
on server logs, I am getting **[0:153]TFTP: lpxelinux.0: transfer error: read udp [::]:33657: i/o timeout**

I am able to do ```tftp <ip> $get lpxelinux.0``` successfully.
How to debug it further ?
Thanks,
