### ISSUE TITLE
DHCP Option 67 - default setting ? 

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#741]
Currently - we support next-server via "magic" ... 

It seems like we should also set the DHCP Option 67 value if not specified to a sane default that support Legacy Boot mode initially, and tries to support as many common variations of UEFI boot mode as possible ... this would allow for more ... "magic" in our subnet settings ... requiring an operator to only modify it if they have a custom environment or odd UEFI boot solution they needed.

An example default might be (though I believe this is not quite right with recent changes ???):

`"lpxelinux.0" {{if (eq (index . 77) "iPXE") }}default.ipxe{{else if (eq (index . 93) "0")}}lpxelinux.0{{else}}bootx64.efi{{end}}`

**Comment by sygibson** [comment]
at it's simplest form if we didn't want to tackle a more all encompassing UEFI version - is to just add:

  `lpxelinux.0`

As the default to automatically support Legacy BIOS firmware mode.

**Comment by galthaus** [comment]
This is already in the code internally if not set.

The issue that drove this is that virtual box is declares itself as ipXe.  DRP responds as such and it hangs.  virtual box must explicitly set lpxelinux.0 because virtual box is busted.

A doc change may be desired.

**Comment by sygibson** [comment]
quickstart doc updated to note VirtualBox iPXE broken - and other enhancements around v3.7.0 magic
