### ISSUE TITLE
Swagger generates an empty schema

### ISSUE THREAD

**Issue by gregbuehler** [digitalrebar/provision#743]
It appears that the swagger definitions are generating an empty schema. The path `/swagger.json` returns the following contents:
```
{
paths: { },
swagger: "2.0"
}
```

**Comment by galthaus** [comment]
hmm - looking.  This is new.

**Comment by gregbuehler** [comment]
For more context: I'm seeing the behavior in the `v3.7.0-tip` Docker image. Did a `docker pull digitalrebar/provision:latest` and still see the same issue.

**Comment by galthaus** [comment]
I see what it is.  We moved a file and forgot to check this.  We are addressing a couple of quick issues and we'll turn something better.  You will even get a v3.7.1 container out of it.
