### ISSUE TITLE
UX: info&pref screen "refresh" does not refresh Preferences

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#764]
ux version:  1.0.2
drp version: 3.7.3

Open UX to the Info & Preferences menu item
Set the Preferences at the CLI 
eg:  ``drpcli prefs set unknownTokenTimeout 12000 knownTokenTimeout 72000``

UX does not recognize a change to this page
"Refresh" only refreshes System Wizard and does not refresh Prefs

Reload page, or navigate away from Info&Prefs, and navigate back does refresh correctly

**Comment by galthaus** [comment]
Tested this and it works.
