### ISSUE TITLE
bzImage flag should not be checked for EFI iPXE

### ISSUE THREAD

**Issue by taliesins** [digitalrebar/provision#823]
I am attempting to use v3.7.3 with gen 2 hyper-v machine. Works great with Gen 1 and legacy adapter. 

On Gen 2 iPXE is going in a boot loop, due to no support for bzImage flag being advertised.

See check here:
https://github.com/digitalrebar/provision/blob/665f50c59e76e32413da0e26dae909cf24653ac3/midlayer/dhcp.go#L230

According to this:
https://github.com/google/netboot/issues/55

> OK, the specific trick here is that EFI iPXE can only boot EFI binaries. The reason linux bzImage seems to work is because the kernels are usually built with CONFIG_EFI_STUB, which makes the bzImage loadable as an EFI binary.
> 
> So, the trick is that when booting via EFI, it's okay to be missing the bzImage feature flag.

If we only checked the bzImage flag when its not EFI, I think it would fix the boot loop. Might fix the problem for a few other systems too.

**Comment by VictorLowther** [comment]
#824 should fix this,

**Comment by galthaus** [comment]
v3.7.3-tip-179-0f71c4d3009e6f2284b86530a952ce92360ec29f or higher should address the issue.

**Comment by taliesins** [comment]
HyperV Gen 1 and Gen 2 machines are working perfectly now.
