### ISSUE TITLE
UX: workflow editor rendering issue w/ non-existent stage

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#827]
In the new workflow editor, if a stage doesn't exist on a workflow, the rendering of the icons after a change causes visual problems.  The (very) rough flow of what I did to get here:

* created ubuntu 18.04 stages/bootenvs and a workflow with them (separate content pieces)
* we added 18.04 to drp-cc, but I changed the names to include "beta" tag in Name
* I updated drp-cc, then deleted the hand crafted Stage/BootEnv

However, the Workflows still contained the reference to the non-existent Stage (ubuntu-18.04-install).

Trying to correct it, I drag-n-dropped the new/correct `ubuntu-18.04-beta-install` stage in to the workflow, which resulted in a rendered view like this:

![screen shot 2018-04-14 at 08 52 15](https://user-images.githubusercontent.com/5308433/38770045-8feaf54a-3fc1-11e8-8690-cd7e6bef6254.png)

I had to hard reload my browser to get the rendering back to clean/usable state. 

I also could not Select a given work flow to see the elements in the left side panel - that functionality broke as well.

**Comment by galthaus** [comment]
This fixed and works much better now.
