### ISSUE TITLE
Can't delete then add tasks to a stage when cloning it

### ISSUE THREAD

**Issue by djp928** [digitalrebar/provision#842]
When cloning a stage, if I try to delete a template and then add a new one, the template numbering does not adjust properly.  For instance, if a stage has one task as task0, if I delete that and add a new one, instead of being task0, it is task1.  Saving the stage then produces an error.  The workaround is to delete all unwanted tasks first, save the new stage, then edit it again to add in the tasks you want.  This avoids the issue.

Versions: DR v3.8.0 & UX v1.1.0

Steps to reproduce:

- Clone a stage in the UI 

![screen shot 2018-04-27 at 3 09 25 pm](https://user-images.githubusercontent.com/30728995/39380731-995aca9e-4a2d-11e8-8f48-d87b2a2345fc.png)
- Delete unwanted task and try to add a new one 

![screen shot 2018-04-27 at 3 09 55 pm](https://user-images.githubusercontent.com/30728995/39380817-e316d150-4a2d-11e8-960c-7a33e24a3f7f.png)
- Try to save the new stage

![screen shot 2018-04-27 at 3 10 09 pm](https://user-images.githubusercontent.com/30728995/39380841-0052454c-4a2e-11e8-80ca-a3e448d06035.png)

**Comment by zehicle** [comment]
this was fixed a while back

**Comment by galthaus** [comment]
This is fixed by my testing.
