### ISSUE TITLE
exploded isos will not be removed

### ISSUE THREAD

**Issue by mash-graz** [digitalrebar/provision#853]
when i use `drpcli isos destroy ...` command, this file gets removed, but the exploded directory in `tftpboot` still exists. is there any command available to force a more adequate cleanup?

**Comment by galthaus** [comment]
The iso gets destroyed, but the tftpboot doesn't because that directory is shared and not directly tied to iso image (because of versioning differences).  Also, a single iso could be exploded to multiple directories.   

Will need to think about this some more.

**Comment by galthaus** [comment]
This is also a duplicate of #437
