### ISSUE TITLE
UX: add bootenv link to stages panel

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#866]
The current Stages detail panel contains links to the Tasks a Stage can run.  This is handy to quickly iterate through content and see what each compossible piece of content looks like. 

Currently UX v1.2.1 and older does not provide a link for a given BootEnv if it is defined in the stage. 

This request is to add a link to the given BootEnv

**Comment by galthaus** [comment]
This would help to have both a bootenv link in the stages table and also the stages edit panel to have quick link to bootevn.

**Comment by galthaus** [comment]
Resolved in tip UX. 1.5.1 +++
