### ISSUE TITLE
Broken Youtube playlist link in documentation

### ISSUE THREAD

**Issue by danderson** [digitalrebar/provision#870]
The playlist link in http://provision.readthedocs.io/en/latest/doc/quickstart.html#videos goes to a "Playlist not found" error page on Youtube.

Spelunking around youtube, I believe the correct link should now be https://www.youtube.com/playlist?list=PLXPBeIrpXjfilUi7Qj1Sl0UhjxNRSC7nx .

**Comment by zehicle** [comment]
fixed
