### ISSUE TITLE
ubuntu-18.04-install produces non-updateable OS

### ISSUE THREAD

**Issue by danderson** [digitalrebar/provision#871]
To reproduce:

 - Enable the drp-community-content package (1.8.0 or tip, both are broken same way)
 - `drpcli bootenvs uploadiso ubuntu-18.04-install`
 - Run a machine through the ubuntu-18.04-install stage
 - Log into the machine, run `apt update`

The output will look something like:

```
root@d06-34-01-22-9e-31:~# apt update
Ign:1 http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease
Ign:2 http://192.168.17.66:8091/ubuntu-18.04/install bionic-updates InRelease
Ign:3 http://192.168.17.66:8091/ubuntu-18.04/install bionic-backports InRelease
Hit:4 http://192.168.17.66:8091/ubuntu-18.04/install bionic Release
Err:5 http://192.168.17.66:8091/ubuntu-18.04/install bionic-updates Release
  404  Not Found [IP: 192.168.17.66 8091]
Err:6 http://192.168.17.66:8091/ubuntu-18.04/install bionic-backports Release                          
  404  Not Found [IP: 192.168.17.66 8091]
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease                                      
Reading package lists... Done                         
E: The repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'universe' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'universe/binary-amd64/Packages' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'universe' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'universe/i18n/Translation-en' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'universe' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'universe/i18n/Translation-en_US' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'universe' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'universe/cnf/Commands-amd64' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'universe' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/binary-amd64/Packages' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/binary-i386/Packages' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/i18n/Translation-en' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/i18n/Translation-en_US' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/cnf/Commands-amd64' as repository 'http://192.168.17.66:8091/ubuntu-18.04/install bionic InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
```

What appears to have happened is that the install seed configured the final OS to source all its packages from the exploded install ISO. This is bad, because the install disk only carries the "main" repository, but the installer assumes a full mirror and configures all the standard sources in `/etc/apt/sources.list`, including the `universe` and `multiverse` sources that are missing from the install disk. This in turn causes `apt update` to fail.

More generally, it would seem that the ubuntu-18.04-install bootenv is not respecting the value of the `local-repo` param. Even setting it to `false` explicitly in the global profile, I get an OS configured to use DRP's mirror.

**Comment by danderson** [comment]
Reading through the preseed documentation... I'm fairly sure you simply cannot use DRP as a mirror in either the debian or ubuntu bootenvs. The debian-family installer assumes that the provided mirror is a complete mirror for all the sources requested. That is not true of any of the install media for either debian or ubuntu.

So, even if ubuntu happens to install successfully off the DRP exploded ISO, most even simple tasks beyond that will fail. And the debian installer just fails hard mid-install, as it discovers that the debian install ISO contains no package mirrors at all, not even a partial one.

As for a fix... The obvious one would be to set a default for the `package-repositories` param, which currently is unset, leading `backend/renderData.go:MachineRepos` to panic and make up some repos on the spot based on the exploded ISO. Alternatively, the "construct repos from exploded ISO" strategy should be skipped entirely for debian-family OSes, since it will never produce a correct OS.

**Comment by danderson** [comment]
Confirmed that by defining `package-repositories` as the following, debian-9-install is able to run through the complete installation.

```json
[{
  "tag": "debian-9-install",
  "os": ["debian-9"],
  "installSource": true,
  "url": "http://mirrors.kernel.org/debian",
  "distribution": "stretch",
  "components": ["main"],
}]
```

**Comment by danderson** [comment]
Agree that setting defaults that produce a working, but non-airgapped system out of the box is a good default.

The only other option I see to provide a reliable airgap setup out of the box would be to ship the entire mirrors for both distros, or teach DRP how to manage such mirrors. While that would definitely be cool, it's a significant undertaking on top of the existing product. I fear trying to work from ISOs alone will always be brittle, especially with the trend towards smaller "netinstall" images in that OS family.

**Comment by sygibson** [comment]
I think we can strike a balance here ... 

- use the exploded out ISOs as the primary install mechanism 
- post install, add the "default" public mirrors - but allow the current @VictorLowther method to overwrite for internal mirrors
- in all cases, honor an `air-gap = true` flag - if set - we automatically turn off the public mirrors - use only the exploded ISO - and the operator has to add internal mirrors for additional install packages

I think that would strike a nice balance - especially in the DRP Community Content - which is oriented more towards the community - which I think as a general practice is a bit more open to using public mirrors.  Commercial users or shops with good internal mirrors can easily override the public mirrors, and security nuts can switch to default secure by setting `air-gap` appropriately.

**Comment by galthaus** [comment]
@sygibson - that is what I said minus the air-gap variable.  I'm against that addition of a variable whose purpose is to alter another parameter in some task as a side-effect.

@danderson - with regard to repo management, I agree that I don't think I'd want to do that for the product proper, right now.  You can do it yourself and use DRP to serve it by managing a directory under the tftpboot directory and use package-repositories to point at that location in DRP.  Not as clean, but doable.

The specific tasks that need to be done to implement this:
* Create a new task that places the MachineRepos into place post install.  This is not done currently.  It was left as an exercise for the reader, but we should just implement this.  It will need to be done for all the operating systems.  While the .MachineRepos returns an object that will work with the .Lines function, it will need to understand the per-OS file location context.  This can then be included as part install stage.
* Add for ubuntu/debian the default machine repos maps (without install Repos set).  This will go in the parameter object as a default.  We may have to add code in DRP to address when parameter defaults are used in the rendering path.
* Enhance documentation to describe the 3 scenarios and how to activate them.

**Comment by VictorLowther** [comment]
Huh, the security issue looks like a new thing for ubuntu 18.04.  I will look at building a set of defaults for package-repositories, but we will also need to take a look at the apt-secure thing and decide how best to handle it.

**Comment by VictorLowther** [comment]
OK, this will be a 2 part fix.
1. Tweak the InstallRepos code to handle more than 1 installSource and securitySource, and bias them towards locallyt expanded install trees.  I will also add lookaside for kernels an initrds for installSources, because debian and ubuntu put them in stupid hard-to-discover locations.  Tweak the MachineRepos code to not have this bias, and include all sources that are present and valid for the machine.  That should bring Debian and Ubunu up to parity with Centos w.r.t not having to upload an ISO to install them.

2. Update drp-community-content to provide a default value for package-repositories that covers OSes we include in drp-community-content, and update the tasks that handle post-install repo munging to use the values from package-repositories.

**Comment by VictorLowther** [comment]
https://github.com/digitalrebar/provision/pull/877 addresses  part of the first part.
