### ISSUE TITLE
Setting "debug" logging level on frontend locks up DRP

### ISSUE THREAD

**Issue by danderson** [digitalrebar/provision#874]
While trying to debug #873, I cranked up the "debug frontend" log level to "debug". As soon as I save this, both the UI and CLI lock up, as if DRP no longer responds to any requests. The only way to restore is to shut down DRP, manually edit the preference json in the datastore to lower the log level to "info" or below, and restart DRP.

**Comment by VictorLowther** [comment]
Hmmm... Can you throw the last 100 or so lines from the log into this issue after replicating the lockup?

**Comment by galthaus** [comment]
I've replicated it on my packet systems.

**Comment by galthaus** [comment]
It generates no logging when it happens.  It seems to be associated with the UX calls.  I could use the drpcli (i tried one action).

**Comment by galthaus** [comment]
The logs I get are this:

[0:191]Claims ok: 'profiles' 'get' 'rackn-license'
dr-provision2018/05/14 14:37:58.807219 [294:192]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:603
[294:192]claim has user id rocketskates
dr-provision2018/05/14 14:37:58.809387 [293:193]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:612
[293:193]claim has user id rocketskates
dr-provision2018/05/14 14:37:58.811866 [295:194]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:612
[295:194]claim has user id rocketskates
dr-provision2018/05/14 14:37:58.812435 [293:195]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[293:195]API: st: 200 lt:   19.590503ms ip:   24.153.228.59 m: GET /api/v3/machines
dr-provision2018/05/14 14:37:58.814200 [313:196]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:603
[313:196]claim has user id rocketskates
dr-provision2018/05/14 14:37:58.816186 [294:197]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:612
[294:197]claim has user id rocketskates
dr-provision2018/05/14 14:37:58.817767 [295:198]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[295:198]API: st: 200 lt:   24.262494ms ip:   24.153.228.59 m: GET /api/v3/stages
dr-provision2018/05/14 14:37:58.818269 [294:199]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[294:199]API: st: 200 lt:   25.387882ms ip:   24.153.228.59 m: GET /api/v3/subnets
dr-provision2018/05/14 14:37:58.818411 [313:200]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:612
[313:200]claim has user id rocketskates
dr-provision2018/05/14 14:37:58.820878 [313:201]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[313:201]API: st: 200 lt:   16.300237ms ip:   24.153.228.59 m: GET /api/v3/profiles/rackn-license
dr-provision2018/05/14 14:37:58.947957 [338:202]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/backend/conncache.go:63
[338:202]addrCache: Renewing local 147.75.73.159 -> remote 24.153.228.59
dr-provision2018/05/14 14:37:58.950143 [341:203]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[341:203]API: st: 200 lt:        9.44µs ip:   24.153.228.59 m: OPTIONS /api/v3/bootenvs
dr-provision2018/05/14 14:37:59.014603 [344:204]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/backend/conncache.go:63
[344:204]addrCache: Renewing local 147.75.73.159 -> remote 24.153.228.59
dr-provision2018/05/14 14:37:59.016963 [0:205]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:578
[0:205]Claims ok: 'bootenvs' 'list' ''
dr-provision2018/05/14 14:37:59.019101 [347:206]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:603
[347:206]claim has user id rocketskates
dr-provision2018/05/14 14:37:59.021232 [347:207]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:612
[347:207]claim has user id rocketskates
dr-provision2018/05/14 14:37:59.026658 [347:208]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[347:208]API: st: 200 lt:     9.88867ms ip:   24.153.228.59 m: GET /api/v3/bootenvs
dr-provision2018/05/14 14:37:59.097865 [356:209]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/backend/conncache.go:63
[356:209]addrCache: Renewing local 147.75.73.159 -> remote 24.153.228.59
dr-provision2018/05/14 14:37:59.115768 [360:210]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/backend/conncache.go:63
[360:210]addrCache: Renewing local 147.75.73.159 -> remote 24.153.228.59
dr-provision2018/05/14 14:37:59.118417 [363:211]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[363:211]API: st: 200 lt:       12.02µs ip:   24.153.228.59 m: OPTIONS /api/v3/prefs
dr-provision2018/05/14 14:37:59.118435 [364:212]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/frontend.go:438
[364:212]API: st: 200 lt:       6.779µs ip:   24.153.228.59 m: OPTIONS /api/v3/isos
dr-provision2018/05/14 14:37:59.153496 [359:213]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/frontend/websocket.go:130
[359:213]Registering for *.*.*
dr-provision2018/05/14 14:37:59.184110 [369:214]frontend [debug]: /home/travis/gopath/src/github.com/digitalrebar/provision/backend/conncache.go:63
[369:214]addrCache: Renewing local 147.75.73.159 -> remote 24.153.228.59

[root@sledgebuild tip]# 
[root@sledgebuild tip]# 
[root@sledgebuild tip]# 
[root@sledgebuild tip]# drpcli prefs list

It may be the registration part of the websocket that the UX is opening to listen for events.

**Comment by galthaus** [comment]
I can do this.  Start dr-provision with base stuff, run `drpcli logs watch` in one terminal.  This has locked up the system.  Running anything in other terminals has the system locked.

**Comment by galthaus** [comment]
This has already been fixed in tip.  The publish/log/auth system was reworked for roles and removed this issue.  Not sure on purpose, but fixed none the less.
