### ISSUE TITLE
UX: add links to Profiles on Machine objects 

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#908]
The Machine object panel shows Profiles, but does not provide a link to that profile.  It would be fabulous if a profile displayed on the machine object contained a link to that Profile. 

![screen shot 2018-06-09 at 17 44 23](https://user-images.githubusercontent.com/5308433/41197278-ed00fb54-6c0c-11e8-849c-c41e9507415a.png)

**Comment by sygibson** [comment]
- changed the title to be a little more broad 

Would also like to see the Profiles listed on a Machine object to have an expansion arrow to show the existing Params in that Profile - without having to click through to the Profile itself - this would make it easier to view the Params associated with a profile applied to a machine via the UX.

**Comment by zehicle** [comment]
This was done. 
I like your idea.
