### ISSUE TITLE
Error while editing stage in RackN Portal

### ISSUE THREAD

**Issue by godfoder** [digitalrebar/provision#931]
When editing a stage, the task list does not automatically update the index of the elements, and blank elements are not ignored when saving. When cloning a stage with the intent of removing one of the middle task elements, this prevents saving the cloned stage.

Reproducing the bug:
1. Start a fresh digital rebar instance (i'm using tip).
2. Go to stages.
3. Select centos-7.5.1804-install, click clone
4. Remove the "centos-drp-only-repos" tasks.
5. click Add

You'll get the error message "Invalid Task ``"

**Comment by zehicle** [comment]
You have to manually remove the blanks - there's delete button for that.  We cannot make assumptions about blanks.

**Comment by zehicle** [comment]
replicated and fixed this issue.  Thanks @godfoder for good documentation.

**Comment by zehicle** [comment]
Will be available in the tip UX after review (likely 7/7)
