### ISSUE TITLE
UX:  setting Params with multiline values breaks other Params

### ISSUE THREAD

**Issue by sygibson** [digitalrebar/provision#934]
- create a Param via the CLI with a multiline string:
   `drpcli profiles add global param "foo/bar" to '"foo\nbar"'`
- in the UX now try and add / remove Params
- this causes problems for editing Params after the multi line Param is injected

**Comment by zehicle** [comment]
my understanding of the issue is that the UX is changing the value by adding \ protections to " and \

**Comment by zehicle** [comment]
Added render:raw as a Meta field in Params that will for UX to use a text area instead of treating params as a string.  This will address the issue.

Note: Params.Meta.render has several other UX options including "machines-map" and "profiles"

**Comment by zehicle** [comment]
drpcli params update foo/foo '{"Meta":{"render":"raw"}}'

**Comment by zehicle** [comment]
fixed
