### ISSUE TITLE
OS.IsoSha256 mismatch for Debian

### ISSUE THREAD

**Issue by hbokh** [digitalrebar/provision#948]
In file `drp-data/saas-content/default.yaml` from "drp-community-content v1.9.0", the OS.IsoSha256 values for Debian 8 and 9 do not reflect the values from the downloaded mini.iso-images.

Real values:
```
debian-8-amd64-mini.iso 61a852072514c385d3a22005bafeb083a2da40efa816a115c4acfa682d112b2b
debian-9-amd64-mini.iso cb0e8a529e2c04b06c5d108f72b22281153df15e26b2b900202ef30ac949e5dd
```

I altered the SHA256sums manually in `drp-data/saas-content/default.yaml` and restarted the `dr-provision` process, but is there a better way to do this?

**Comment by galthaus** [comment]
Sadly, not really.  When the distro providers update their releases, we have to update ours.  Thanks for pointing this out.

**Comment by zehicle** [comment]
@hbokh - Greg was talking about the checksum half life.  if you are asking about the dr-server restart, then YES, there is a much better way to do that.  You need to checkout the git content then use drpcli contents bundle and drpcli contents upload.  The process is explained in the docs and several videos.

We work hard to ensure that you do NOT need to restart the service.
